apiVersion: v1
kind: ServiceAccount
metadata:
  name: faultlab
  namespace: fault-lab
  labels:
    app.kubernetes.io/part-of: aegisops
    app.kubernetes.io/component: fault-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faultlab
  namespace: fault-lab
  labels:
    app.kubernetes.io/part-of: aegisops
    app.kubernetes.io/component: fault-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: faultlab
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: faultlab
        app.kubernetes.io/part-of: aegisops
    spec:
      serviceAccountName: faultlab
      containers:
        - name: faultlab
          image: aegisops.local/fault-lab:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: ":8080"
            - name: CHAOS_ENABLED
              value: "true"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: { cpu: 10m, memory: 32Mi }
            limits: { cpu: 200m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: faultlab
  namespace: fault-lab
  labels:
    app.kubernetes.io/part-of: aegisops
    app.kubernetes.io/component: fault-lab
    app.kubernetes.io/instance: faultlab
spec:
  selector:
    app.kubernetes.io/instance: faultlab
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: faultlab
  namespace: fault-lab
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: aegisops
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: faultlab
  endpoints:
    - port: http
      path: /metrics
