{{- if .Values.observability.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegisops.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegisops.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aegisops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aegisops.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegisops.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "aegisops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
