//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIOpsIncident) DeepCopyInto(out *AIOpsIncident) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIOpsIncident.
func (in *AIOpsIncident) DeepCopy() *AIOpsIncident {
	if in == nil {
		return nil
	}
	out := new(AIOpsIncident)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIOpsIncident) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIOpsIncidentList) DeepCopyInto(out *AIOpsIncidentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIOpsIncident, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIOpsIncidentList.
func (in *AIOpsIncidentList) DeepCopy() *AIOpsIncidentList {
	if in == nil {
		return nil
	}
	out := new(AIOpsIncidentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIOpsIncidentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIOpsIncidentSpec) DeepCopyInto(out *AIOpsIncidentSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.LastReceivedAt.DeepCopyInto(&out.LastReceivedAt)
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
	if in.CommonLabels != nil {
		in, out := &in.CommonLabels, &out.CommonLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CommonAnnotations != nil {
		in, out := &in.CommonAnnotations, &out.CommonAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIOpsIncidentSpec.
func (in *AIOpsIncidentSpec) DeepCopy() *AIOpsIncidentSpec {
	if in == nil {
		return nil
	}
	out := new(AIOpsIncidentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIOpsIncidentStatus) DeepCopyInto(out *AIOpsIncidentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = new(EvidenceSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(AnalysisReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Diagnosis != nil {
		in, out := &in.Diagnosis, &out.Diagnosis
		*out = new(DiagnosisSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Proposal != nil {
		in, out := &in.Proposal, &out.Proposal
		*out = new(ActionProposal)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyDecision != nil {
		in, out := &in.PolicyDecision, &out.PolicyDecision
		*out = new(PolicyDecisionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Approval != nil {
		in, out := &in.Approval, &out.Approval
		*out = new(ApprovalStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(VerificationSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeline != nil {
		in, out := &in.Timeline, &out.Timeline
		*out = make([]TimelineEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIOpsIncidentStatus.
func (in *AIOpsIncidentStatus) DeepCopy() *AIOpsIncidentStatus {
	if in == nil {
		return nil
	}
	out := new(AIOpsIncidentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionPolicy) DeepCopyInto(out *ActionPolicy) {
	*out = *in
	if in.MaxReplicaDelta != nil {
		in, out := &in.MaxReplicaDelta, &out.MaxReplicaDelta
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxCPU != nil {
		in, out := &in.MaxCPU, &out.MaxCPU
		*out = new(ResourceQuantity)
		**out = **in
	}
	if in.MaxMemory != nil {
		in, out := &in.MaxMemory, &out.MaxMemory
		*out = new(ResourceQuantity)
		**out = **in
	}
	if in.MaxIncreasePercent != nil {
		in, out := &in.MaxIncreasePercent, &out.MaxIncreasePercent
		*out = new(int32)
		**out = **in
	}
	if in.MaxRevisionDistance != nil {
		in, out := &in.MaxRevisionDistance, &out.MaxRevisionDistance
		*out = new(int64)
		**out = **in
	}
	if in.AllowedNames != nil {
		in, out := &in.AllowedNames, &out.AllowedNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireImmutableBackup != nil {
		in, out := &in.RequireImmutableBackup, &out.RequireImmutableBackup
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionPolicy.
func (in *ActionPolicy) DeepCopy() *ActionPolicy {
	if in == nil {
		return nil
	}
	out := new(ActionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionProposal) DeepCopyInto(out *ActionProposal) {
	*out = *in
	in.Parameters.DeepCopyInto(&out.Parameters)
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionProposal.
func (in *ActionProposal) DeepCopy() *ActionProposal {
	if in == nil {
		return nil
	}
	out := new(ActionProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisReference) DeepCopyInto(out *AnalysisReference) {
	*out = *in
	if in.SubmittedAt != nil {
		in, out := &in.SubmittedAt, &out.SubmittedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisReference.
func (in *AnalysisReference) DeepCopy() *AnalysisReference {
	if in == nil {
		return nil
	}
	out := new(AnalysisReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalStatus) DeepCopyInto(out *ApprovalStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
	if in.DecidedAt != nil {
		in, out := &in.DecidedAt, &out.DecidedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalStatus.
func (in *ApprovalStatus) DeepCopy() *ApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(ApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisSummary) DeepCopyInto(out *DiagnosisSummary) {
	*out = *in
	if in.EvidenceIDs != nil {
		in, out := &in.EvidenceIDs, &out.EvidenceIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RunbookRefs != nil {
		in, out := &in.RunbookRefs, &out.RunbookRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisSummary.
func (in *DiagnosisSummary) DeepCopy() *DiagnosisSummary {
	if in == nil {
		return nil
	}
	out := new(DiagnosisSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceSummary) DeepCopyInto(out *EvidenceSummary) {
	*out = *in
	in.Window.DeepCopyInto(&out.Window)
	if in.Counts != nil {
		in, out := &in.Counts, &out.Counts
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceSummary.
func (in *EvidenceSummary) DeepCopy() *EvidenceSummary {
	if in == nil {
		return nil
	}
	out := new(EvidenceSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionReference) DeepCopyInto(out *ExecutionReference) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionReference.
func (in *ExecutionReference) DeepCopy() *ExecutionReference {
	if in == nil {
		return nil
	}
	out := new(ExecutionReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecutionStatus) DeepCopyInto(out *ExecutionStatus) {
	*out = *in
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(ExecutionReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecutionStatus.
func (in *ExecutionStatus) DeepCopy() *ExecutionStatus {
	if in == nil {
		return nil
	}
	out := new(ExecutionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentReference) DeepCopyInto(out *IncidentReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentReference.
func (in *IncidentReference) DeepCopy() *IncidentReference {
	if in == nil {
		return nil
	}
	out := new(IncidentReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRevision) DeepCopyInto(out *ObjectRevision) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRevision.
func (in *ObjectRevision) DeepCopy() *ObjectRevision {
	if in == nil {
		return nil
	}
	out := new(ObjectRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDecisionStatus) DeepCopyInto(out *PolicyDecisionStatus) {
	*out = *in
	if in.ReasonCodes != nil {
		in, out := &in.ReasonCodes, &out.ReasonCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DecidedAt != nil {
		in, out := &in.DecidedAt, &out.DecidedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDecisionStatus.
func (in *PolicyDecisionStatus) DeepCopy() *PolicyDecisionStatus {
	if in == nil {
		return nil
	}
	out := new(PolicyDecisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApproval) DeepCopyInto(out *RemediationApproval) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApproval.
func (in *RemediationApproval) DeepCopy() *RemediationApproval {
	if in == nil {
		return nil
	}
	out := new(RemediationApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationApproval) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalList) DeepCopyInto(out *RemediationApprovalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalList.
func (in *RemediationApprovalList) DeepCopy() *RemediationApprovalList {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationApprovalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalSpec) DeepCopyInto(out *RemediationApprovalSpec) {
	*out = *in
	out.IncidentRef = in.IncidentRef
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalSpec.
func (in *RemediationApprovalSpec) DeepCopy() *RemediationApprovalSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationApprovalStatus) DeepCopyInto(out *RemediationApprovalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProcessedAt != nil {
		in, out := &in.ProcessedAt, &out.ProcessedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationApprovalStatus.
func (in *RemediationApprovalStatus) DeepCopy() *RemediationApprovalStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationApprovalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicy) DeepCopyInto(out *RemediationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicy.
func (in *RemediationPolicy) DeepCopy() *RemediationPolicy {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicyList) DeepCopyInto(out *RemediationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicyList.
func (in *RemediationPolicyList) DeepCopy() *RemediationPolicyList {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicySpec) DeepCopyInto(out *RemediationPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make(map[ActionType]ActionPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.VerificationWindow != nil {
		in, out := &in.VerificationWindow, &out.VerificationWindow
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ApprovalTTL != nil {
		in, out := &in.ApprovalTTL, &out.ApprovalTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RequireAudit != nil {
		in, out := &in.RequireAudit, &out.RequireAudit
		*out = new(bool)
		**out = **in
	}
	if in.RollbackOnVerificationFailure != nil {
		in, out := &in.RollbackOnVerificationFailure, &out.RollbackOnVerificationFailure
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicySpec.
func (in *RemediationPolicySpec) DeepCopy() *RemediationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationPolicyStatus) DeepCopyInto(out *RemediationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastValidatedAt != nil {
		in, out := &in.LastValidatedAt, &out.LastValidatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationPolicyStatus.
func (in *RemediationPolicyStatus) DeepCopy() *RemediationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSelector) DeepCopyInto(out *TargetSelector) {
	*out = *in
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.WorkloadLabels != nil {
		in, out := &in.WorkloadLabels, &out.WorkloadLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSelector.
func (in *TargetSelector) DeepCopy() *TargetSelector {
	if in == nil {
		return nil
	}
	out := new(TargetSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWindow) DeepCopyInto(out *TimeWindow) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWindow.
func (in *TimeWindow) DeepCopy() *TimeWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimelineEntry) DeepCopyInto(out *TimelineEntry) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimelineEntry.
func (in *TimelineEntry) DeepCopy() *TimelineEntry {
	if in == nil {
		return nil
	}
	out := new(TimelineEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationCheck) DeepCopyInto(out *VerificationCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationCheck.
func (in *VerificationCheck) DeepCopy() *VerificationCheck {
	if in == nil {
		return nil
	}
	out := new(VerificationCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationSummary) DeepCopyInto(out *VerificationSummary) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]VerificationCheck, len(*in))
		copy(*out, *in)
	}
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = (*in).DeepCopy()
	}
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationSummary.
func (in *VerificationSummary) DeepCopy() *VerificationSummary {
	if in == nil {
		return nil
	}
	out := new(VerificationSummary)
	in.DeepCopyInto(out)
	return out
}
