apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus-main
    type: prometheus
    access: proxy
    url: http://host.docker.internal:19090
    isDefault: true
  - name: Tempo
    uid: tempo-main
    type: tempo
    access: proxy
    url: http://host.docker.internal:13200
    jsonData:
      httpMethod: GET
  - name: Loki
    uid: loki-main
    type: loki
    access: proxy
    url: http://host.docker.internal:13100
